@startuml
'https://plantuml.com/sequence-diagram

autonumber

User --> FibonacciRecursive:fibonacciRecursive(int n)

FibonacciRecursive -> FibonacciRecursive : conditions

alt n <= 1
FibonacciRecursive --> User: return n

else n > 1
FibonacciRecursive -> FibonacciRecursive : find fibonacciRecursive(n)
FibonacciRecursive --> User: return fibonacciRecursive(n - 1) + fibonacciRecursive(n - 2);

end
@enduml